### ISSUE TITLE
Cannot create project by composer

### ISSUE THREAD

**Issue by ziofat** [andrey900/Flight-Skeleton#1]
When I use 
`composer create-project andrey900/Flight-Skeleton path/to/install`
It says:
Could not find package andrey900/flight-skeleton with stability stable.

**Comment by andrey900** [comment]
So there really is not a package in composer. Due uninteresting solutions and low activity decided not to create package.

**Comment by ziofat** [comment]
But you do have this instruction in readme. I suggest remove it anyway.
